### ISSUE TITLE
Fatal error:  Uncaught Error: Class 'Redux' not found 

### ISSUE THREAD

**Issue by chopinesque** [MohammedKaludi/plugin-manager#4]
I had to remove it as it brought down the site (white screen of death).

```
[30-Jun-2018 18:50:27 UTC] PHP Fatal error:  Uncaught Error: Class 'Redux' not found in /home/mysite/public_html/wp-content/plugins/amp-plugin-manager/ampforwp-3rd-party-plugin-creator.php:148
Stack trace:
#0 /home/mysite/public_html/wp-settings.php(305): include_once()
#1 /home/mysite/public_html/wp-config.php(85): require_once('/home/mysite/p...')
#2 /home/mysite/public_html/wp-load.php(37): require_once('/home/mysite/p...')
#3 /home/mysite/public_html/wp-blog-header.php(13): require_once('/home/mysite/p...')
#4 /home/mysite/public_html/index.php(17): require('/home/mysite/p...')
#5 {main}
  thrown in /home/mysite/public_html/wp-content/plugins/amp-plugin-manager/ampforwp-3rd-party-plugin-creator.php on line 148

```

**Comment by MohammedKaludi** [comment]
Thank you very much for reporting the issue, we have fixed the issue here https://github.com/ahmedkaludi/amp-plugin-manager/commit/9e181c0c17e7962227254cfd2b18e3cf56ab9c2a 

As far as white screen of death is concerned we have fixed and pushed the update please update the core pluign to 0.9.97.2 and it will be fixed.

Also also in the next update that is 0.9.98 the pluign manager issue will also be resolved.

**Comment by gubatron** [comment]
This issue has resurfaced with your last update  0.9.97.43. 

Full wordpress crash when updating from Version 0.9.97.42 to Version 0.9.97.43

**ampforwp-3rd-party-plugin-creator.php:148**

```bash
2019-03-24 19:16:35: (mod_fastcgi.c.2543) FastCGI-stderr: PHP message: PHP Fatal error:  Uncaught Error: Class 'Redux' not found in /mnt/ebs/frostclick-jan-2016-vol-b9afa144/www.frostclick.com/wp/wp-content/plugins/amp-plugin-manager/ampforwp-3rd-party-plugin-creator.php:148
2019-03-24 19:16:35: (mod_fastcgi.c.2543) FastCGI-stderr: Stack trace:
2019-03-24 19:16:35: (mod_fastcgi.c.2543) FastCGI-stderr: #0 /mnt/ebs/frostclick-jan-2016-vol-b9afa144/www.frostclick.com/wp/wp-settings.php(342): include_once()
2019-03-24 19:16:35: (mod_fastcgi.c.2543) FastCGI-stderr: #1 /mnt/ebs/frostclick-jan-2016-vol-b9afa144/www.frostclick.com/wp/wp-config.php(98): require_once('/mnt/ebs/frostc...')
2019-03-24 19:16:35: (mod_fastcgi.c.2543) FastCGI-stderr: #2 /mnt/ebs/frostclick-jan-2016-vol-b9afa144/www.frostclick.com/wp/wp-load.php(37): require_once('/mnt/ebs/frostc...')
2019-03-24 19:16:35: (mod_fastcgi.c.2543) FastCGI-stderr: #3 /mnt/ebs/frostclick-jan-2016-vol-b9afa144/www.frostclick.com/wp/wp-admin/admin.php(34): require_once('/mnt/ebs/frostc...')
2019-03-24 19:16:35: (mod_fastcgi.c.2543) FastCGI-stderr: #4 /mnt/ebs/frostclick-jan-2016-vol-b9afa144/www.frostclick.com/wp/wp-admin/plugins.php(10): require_once('/mnt/ebs/frostc...')
2019-03-24 19:16:35: (mod_fastcgi.c.2543) FastCGI-stderr: #5 {main}
2019-03-24 19:16:35: (mod_fastcgi.c.2543) FastCGI-stderr:   thrown in /mnt/ebs/frostclick-jan-2016-vol-b9afa144/www.frostclick.com/wp/wp-content/plugins/amp-plugin-manager/ampforwp-3rd-party-plugin-creator.php on line 148
2019-03-24 19:16:41: (mod_fastcgi.c.2543) FastCGI-stderr: PHP message: PHP Fatal error:  Uncaught Error: Class 'Redux' not found in /mnt/ebs/frostclick-jan-2016-vol-b9afa144/www.frostclick.com/wp/wp-content/plugins/amp-plugin-manager/ampforwp-3rd-party-plugin-creator.php:148

```
